[build]
  base = "" # Root of the monorepo
  publish = "frontend/build" # Path to the directory where the site files are stored after build
  command = "npm run build --prefix frontend" # Command to build the frontend app

[dev]
  command = "npm run start --prefix frontend" # Command to start the frontend app locally

[functions]
  directory = "netlify/functions" # Directory for serverless functions (if any)
